# Generated by Django 4.0.2 on 2022-11-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dars',
            name='dars',
        ),
        migrations.AlterField(
            model_name='dars',
            name='kalit',
            field=models.CharField(max_length=4, verbose_name='Kalit'),
        ),
    ]
